stages:
  - build
  - test
  - deploy
  - notify

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ~/.conan2

variables:
  DOCKER_IMAGE: ecs_image
  DISCORD_WEBHOOK_URL: $DISCORD_WEBHOOK_URL 
  GITHUB_SSH_KEY: $GITHUB_SSH_KEY           

build:
  stage: build
  script:
    - conan install . --build=missing
    - docker build -f Dockerfile.ecs -t $DOCKER_IMAGE .
    - docker run $DOCKER_IMAGE cmake .
    - docker run $DOCKER_IMAGE make
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - docker run $DOCKER_IMAGE ./run_tests.sh

deploy:
  stage: deploy
  only:
    - main
  script:
    - echo "Tests passed. Deploying to Epitech repo."
    - mkdir -p ~/.ssh
    - echo "$GITHUB_SSH_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - git config --global user.name "GitLab CI/CD"
    - git config --global user.email "damien.defer@epitech.eu"
    - git remote add epitech git@github.com:EpitechPromo2027/B-CPP-500-NCE-5-2-rtype-leonard.oursel.git
    - git push epitech main

notify:
  stage: notify
  needs: ["deploy"]
  script:
    - |
      curl -H "Content-Type: application/json" -X POST -d '{
        "content": null,
        "embeds": [{
          "title": "CI/CD Pipeline Passed",
          "description": "The CI/CD pipeline for **R-Type** has successfully passed, and the project has been deployed to the Epitech repo.",
          "color": 3066993,
          "fields": [
            {
              "name": "Stage",
              "value": "Deploy"
            },
            {
              "name": "Status",
              "value": "Success"
            }
          ],
          "footer": {
            "text": "CI/CD Notifications"
          },
          "timestamp": "'$(date --utc +%Y-%m-%dT%H:%M:%SZ)'"
        }]
      }' $DISCORD_WEBHOOK_URL
