version: '3.8'

services:
  ecs:
    build:
      context: .
      dockerfile: Dockerfile.ecs
    volumes:
      - ./ecs:/ecs

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - ./server:/server

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    volumes:
      - ./client:/client
