name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
    
      - name: Update and initialize submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive
      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libxcb-util-dev \
            libxcb-util0-dev
      - name: Install Dependencies
        run: |
          sudo rm -rf /var/lib/apt/lists/lock
          sudo rm -rf /var/cache/apt/archives/lock
          sudo apt update
          sudo apt install -y \
            build-essential clang libssl-dev \
            build-essential \
            clang \
            libudev-dev \
            libssl-dev \
            cmake \
            python3-pip \
            git \
            curl \
            pkg-config \
            systemd \
            libsystemd-dev \
            libglvnd-dev \
            libgl1-mesa-dev \
            autoconf \
            automake \
            libtool \
            libx11-dev \
            libx11-xcb-dev \
            libfontenc-dev \
            libice-dev \
            libsm-dev \
            libxau-dev \
            libxaw7-dev \
            libxcomposite-dev \
            libxcursor-dev \
            libxdamage-dev \
            libxext-dev \
            libxfixes-dev \
            libxi-dev \
            libxinerama-dev \
            libxkbfile-dev \
            libxmu-dev \
            libxmuu-dev \
            libxpm-dev \
            libxrandr-dev \
            libxrender-dev \
            libxres-dev \
            libxss-dev \
            libxt-dev \
            libxtst-dev \
            libxv-dev \
            libxxf86vm-dev \
            libxcb-glx0-dev \
            libxcb-render0-dev \
            libxcb-render-util0-dev \
            libxcb-xkb-dev \
            libxcb-icccm4-dev \
            libxcb-image0-dev \
            libxcb-keysyms1-dev \
            libxcb-randr0-dev \
            libxcb-shape0-dev \
            libxcb-sync-dev \
            libxcb-xfixes0-dev \
            libxcb-xinerama0-dev \
            libxcb-dri3-dev \
            uuid-dev \
            libxcb-cursor-dev \
            libxcb-dri2-0-dev \
            libxcb-dri3-dev \
            libxcb-present-dev \
            libxcb-composite0-dev \
            libxcb-ewmh-dev \
            libxcb-res0-dev
      - name: Install Conan
        run: |
          python3 -m pip install --upgrade pip
          pip3 install conan
      - name: Configure Conan Profile
        run: |
          mkdir -p ~/.conan2/profiles
          echo "[settings]" > ~/.conan2/profiles/default
          echo "arch=x86_64" >> ~/.conan2/profiles/default
          echo "build_type=Release" >> ~/.conan2/profiles/default
          echo "compiler=gcc" >> ~/.conan2/profiles/default
          echo "compiler.version=10" >> ~/.conan2/profiles/default  # Ou votre version GCC
          echo "compiler.libcxx=libstdc++11" >> ~/.conan2/profiles/default
          echo "compiler.cppstd=14" >> ~/.conan2/profiles/default
          echo "os=Linux" >> ~/.conan2/profiles/default
   

      # - name: Configure Conan for Server
      #   run: |
      #     cd Server/
      #     conan profile detect

      - name: Install and Build Server
        run: |
          mkdir -p Server/build
          cd Server/build
          conan install .. --output-folder=. --build=missing -c tools.system.package_manager:mode=disabled
          cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release

      - name: Run Tests for Server
        run: |
          cd Server/build
          ctest -C Release --output-on-failure


      - name: Install Dependencies for Client
        run: |
          cd Client/
          mkdir build
          cd build
          conan install .. --output-folder=. --build=missing -c tools.system.package_manager:mode=disabled
      - name: Configure CMake for Client
        run: |
          cd Client/build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
      - name: Build Client
        run: |
          cd Client/build
          cmake --build . --config Release
      - name: Run Tests for Client
        run: |
          cd Client/build
          ctest -C Release --output-on-failure


      - name: Build ECS
        run: |
          mkdir -p ECS/ECS/build
          cd ECS/ECS/build
          conan install .. --output-folder=. --build=missing -c tools.system.package_manager:mode=disabled
          cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
      - name: Run Tests for ECS
        run: |
          cd ECS/ECS/build
          ctest -C Release --output-on-failure
      # - name: Configure Conan for Client
      #   run: |
      #     cd Client/
      #     conan profile detect

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Update and initialize submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan

      - name: Install Visual Studio Build Tools
        run: choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.Windows10SDK.19041"

      - name: Install pkg-config
        run: |
          choco install pkgconfiglite -y
          echo "C:\ProgramData\chocolatey\bin"
          pkg-config --version

      - name: Add pkgconfiglite to PATH
        run: |
          echo "C:\ProgramData\chocolatey\bin" >> $GITHUB_PATH

      - name: Setup Conan for Windows
        run: |
          mkdir -p ~/.conan2/profiles
          echo "[settings]" > ~/.conan2/profiles/default
          echo "arch=x86_64" >> ~/.conan2/profiles/default
          echo "build_type=Release" >> ~/.conan2/profiles/default
          echo "compiler=msvc" >> ~/.conan2/profiles/default
          echo "compiler.version=193" >> ~/.conan2/profiles/default
          echo "compiler.runtime=dynamic" >> ~/.conan2/profiles/default
          echo "compiler.cppstd=17" >> ~/.conan2/profiles/default
          echo "os=Windows" >> ~/.conan2/profiles/default

      - name: Build Project
        shell: cmd
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\VsDevCmd.bat" -arch=amd64
          cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release

      # - name: Configure Conan for Server
      #   shell: bash
      #   run: |
      #     cd Server/
      #     conan profile detect

      - name: Install Dependencies for Server
        shell: bash
        run: |
          cd Server
          mkdir build
          cd build
          conan install .. --output-folder=. --build=missing -c tools.system.package_manager:mode=install

      - name: Configure CMake for Server
        shell: bash
        run: |
          cd Server/build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release

      - name: Build Server
        shell: bash
        run: |
          cd Server/build
          cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="/W4"
          cmake --build . --config Release

      - name: Run Tests for Server
        shell: bash
        run: |
          cd Server/build
          ctest -C Release --output-on-failure

      - name: Build ECS
        shell: bash
        run: |
          mkdir -p ECS/build
          cd ECS/build
          conan install .. --output-folder=. --build=missing -c tools.system.package_manager:mode=install
          cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
          cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="/W4"
          cmake --build . --config Release

      - name: Run Tests for ECS
        shell: bash
        run: |
          cd build
          ctest -C Release --output-on-failure

      - name: Run Tests for ECS
        shell: bash
        run: |
          cd ECS/ECS/build
          ctest -C Release --output-on-failure


      # - name: Configure Conan for Client
      #   shell: bash
      #   run: |
      #     cd Client/
      #     conan profile detect

      - name: Install Dependencies for Client
        shell: bash
        run: |
          cd Client/
          mkdir build
          cd build
          conan install .. --output-folder=. --build=missing -c tools.system.package_manager:mode=install

      - name: Configure CMake for Client
        shell: bash
        run: |
          cd Client/build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release

      - name: Build Client
        shell: bash
        run: |
          cd Client/build
          cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="/W4"
          cmake --build . --config Release

      - name: Run Tests for Client
        shell: bash
        run: |
          cd Client/build
          ctest -C Release --output-on-failure


  mirror:
    # needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Mirror Repository
        run: |
          git remote add mirror ${{ secrets.MIRROR_REPOSITORY_URL }}
          git push --mirror mirror
        env:
          GIT_SSH_COMMAND: "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no"

  notify:
    runs-on: ubuntu-latest
    needs: [ build-linux, build-windows ]
    steps:
      - name: Read Test Results
        id: read-results
        run: |
          if [[ -f Devops/ECS/ECS/test_results.json ]]; then
            RESULTS=$(cat Devops/ECS/ECS/test_results.json)
          else
            RESULTS="[]"
          fi
          echo "::set-output name=results::$RESULTS"

      - name: Notify via Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          TEST_RESULTS="${{ steps.read-results.outputs.results }}"

          FIELDS=""
          STATUS="Success"

          while IFS= read -r line; do
            TEST_NAME=$(echo "$line" | jq -r '.name')
            TEST_STATUS=$(echo "$line" | jq -r '.status')
            TEST_DETAILS=$(echo "$line" | jq -r '.details')

            if [[ "$TEST_STATUS" == "Failure" ]]; then
              STATUS="Failure"
            fi

            FIELDS="${FIELDS},{\"name\": \"${TEST_NAME}\", \"value\": \"${TEST_STATUS} - ${TEST_DETAILS}\", \"inline\": true}"
          done < <(echo "$TEST_RESULTS" | jq -c '.[]')

          if [[ "$STATUS" == "Success" ]]; then
            COLOR=3066993
            TITLE="✅ All Tests Passed"
          else
            COLOR=15158332
            TITLE="❌ Some Tests Failed"
          fi

          curl -H "Content-Type: application/json" -X POST -d "{
            \"content\": null,
            \"embeds\": [{
              \"title\": \"$TITLE\",
              \"description\": \"**EPITECH-RType/Tests**\",
              \"color\": $COLOR,
              \"fields\": [${FIELDS#,*}],
              \"footer\": {\"text\": \"CI/CD Notifications\"},
              \"timestamp\": \"$(date --utc +%Y-%m-%dT%H:%M:%SZ)\"
            }]
          }" $DISCORD_WEBHOOK_URL


#jobs:
#  build-and-test:
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [ubuntu-latest]
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      # Étapes pour Windows (commentées pour l'instant)
##      - name: Install Dependencies (Windows)
##        if: matrix.os == 'windows-latest'
##        run: |
##          choco source add -n community -s https://community.chocolatey.org/api/v2/
##          choco install -y cmake.install git curl llvm mingw
##          where clang-tidy || echo "clang-tidy not installed!"
##          where clang-format || echo "clang-format not installed!"
#
#      - name: Build Docker Image
#        if: matrix.os == 'ubuntu-latest'
#        working-directory: Devops/ECS
#        run: docker build -t ecs_image -f Dockerfile.ecs .
#
##      - name: Build Docker Image (Windows)
##        if: matrix.os == 'windows-latest'
##        working-directory: Devops/ECS
##        run: docker build -t ecs_image -f Dockerfile.windows.ecs .
#
#      - name: Run ECS Tests
#        if: matrix.os == 'ubuntu-latest'
#        working-directory: Devops/ECS
#        run: |
#          docker run ecs_image bash -c "../run_tests.sh"
#
#      # Étape 4 : Tests pour Server (commenté pour le moment)
#      # - name: Build Docker Image for Server
#      #   if: matrix.os == 'ubuntu-latest'
#      #   working-directory: Devops/Server
#      #   run: docker build -t server_image -f Dockerfile.server .
#
#      # - name: Run Server Tests
#      #   working-directory: Devops/Server
#      #   run: |
#      #     docker run server_image bash -c "./run_tests.sh"
#
#      # Étape 5 : Tests pour Client (commenté pour le moment)
#      # - name: Build Docker Image for Client
#      #   if: matrix.os == 'ubuntu-latest'
#      #   working-directory: Devops/Client
#      #   run: docker build -t client_image -f Dockerfile.client .
#
#      # - name: Run Client Tests
#      #   working-directory: Devops/Client
#      #   run: |
#      #     docker run client_image bash -c "./run_tests.sh"
#
#  deploy:
#    runs-on: ubuntu-latest
#    needs: build-and-test
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Configure SSH
#        run: |
#          mkdir -p ~/.ssh
#          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
#          chmod 600 ~/.ssh/id_rsa
#          eval "$(ssh-agent -s)"
#          ssh-add ~/.ssh/id_rsa
#          ssh-keyscan github.com >> ~/.ssh/known_hosts
#
#      - name: Configure Git Identity
#        run: |
#          git config --global user.name "GitHub Actions"
#          git config --global user.email "actions@github.com"
#
#      - name: Force Push Branch to Epitech Repo
#        run: |
#          git remote remove epitech || true
#          git remote add epitech git@github.com:EpitechPromo2027/B-CPP-500-NCE-5-2-rtype-leonard.oursel.git
#          git fetch epitech main || true
#          git reset --hard epitech/main || true
#          git push --force epitech main
