name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        working-directory: Devops/ECS
        run: docker build -f Dockerfile.ecs -t ecs_image .

      - name: Build project inside Docker
        working-directory: Devops/ECS
        run: |
          docker run ecs_image cmake .
          docker run ecs_image make

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Pull latest changes from Epitech repo
        continue-on-error: true  # Continue même si ça échoue, pour éviter les blocages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "your_email@example.com"
          git remote add epitech git@github.com:EpitechPromo2027/B-CPP-500-NCE-5-2-rtype-leonard.oursel.git
          git pull epitech main --rebase || echo "Pull failed, continuing with push."

      - name: Deploy to Epitech repo
        run: |
          git push --mirror epitech

  notify:
    runs-on: ubuntu-latest
    needs: [build, deploy]
    steps:
      - name: Notify via Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          if [[ $GITHUB_JOB == "success" ]]; then
            curl -H "Content-Type: application/json" -X POST -d '{
              "content": null,
              "embeds": [{
                "title": "CI/CD Pipeline Passed",
                "description": "The CI/CD pipeline for **R-Type** has successfully passed, and the project has been deployed to the Epitech repo.",
                "color": 3066993,
                "fields": [
                  {"name": "Stage", "value": "Deploy"},
                  {"name": "Status", "value": "Success"}
                ],
                "footer": {"text": "CI/CD Notifications"},
                "timestamp": "'$(date --utc +%Y-%m-%dT%H:%M:%SZ)'"
              }]
            }' $DISCORD_WEBHOOK_URL
          else
            curl -H "Content-Type: application/json" -X POST -d '{
              "content": null,
              "embeds": [{
                "title": "CI/CD Pipeline Failed",
                "description": "The CI/CD pipeline for **R-Type** has failed. Check the logs for more details.",
                "color": 15158332,
                "fields": [
                  {"name": "Stage", "value": "Failed Stage: $GITHUB_JOB"},
                  {"name": "Status", "value": "Failure"}
                ],
                "footer": {"text": "CI/CD Notifications"},
                "timestamp": "'$(date --utc +%Y-%m-%dT%H:%M:%SZ)'"
              }]
            }' $DISCORD_WEBHOOK_URL
          fi
